language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash ./.travis-docker.sh
env:
 global:
   - PINS="mirage-dns:. dns-async:. dns-lwt:. dns-lwt-unix:."
   - PACKAGE="dns"
   - DEPOPTS="dns-async dns-lwt dns-lwt-unix"
   - PRE_INSTALL_HOOK="cd /home/opam/opam-repository && git pull origin master && opam update -u -y"
 matrix:
   - DISTRO=debian-stable OCAML_VERSION=4.04
   - DISTRO=ubuntu-lts OCAML_VERSION=4.05 DEPOPTS="mirage-dns dns-async dns-lwt dns-lwt-unix"
   - DISTRO=alpine OCAML_VERSION=4.06 DEPOPTS="mirage-dns dns-async dns-lwt dns-lwt-unix"
   - DISTRO=fedora OCAML_VERSION=4.07 DEPOPTS="mirage-dns dns-async dns-lwt dns-lwt-unix"
